name: netnode
version: 0.0.1
description: A sample web application
dependencies:
  angular: 0.10.0
  browser: any
  js: any
  shadow_dom: any
  http_server: any
  route_hierarchical: '>=0.4.18 <0.5.0'
dev_dependencies:
  unittest: any
transformers:
- angular